# Generated by Django 4.2.11 on 2026-06-02 13:35

import django.db.models.deletion
from django.db import migrations, models

import apps.authentication.crypto_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            ("pin_reset", "PIN Reset"),
                        ],
                        default="verification",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "profile_code",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", apps.authentication.crypto_utils.EncryptedTextField(default="")),
                (
                    "email_hashed",
                    models.CharField(db_index=True, default="", max_length=64, unique=True),
                ),
                ("email_masked", models.CharField(default="", max_length=255)),
                (
                    "mobile",
                    apps.authentication.crypto_utils.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "mobile_hashed",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("mobile_masked", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile_images/"),
                ),
                ("password", apps.authentication.crypto_utils.EncryptedTextField(default="")),
                ("password_hashed", models.CharField(default="", max_length=128)),
                ("password_masked", models.CharField(default="", max_length=255)),
                ("pin", apps.authentication.crypto_utils.EncryptedTextField(blank=True, null=True)),
                ("pin_hashed", models.CharField(blank=True, max_length=128, null=True)),
                ("pin_masked", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ADMIN", "Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="auth.group",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all "
                            "permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
