# Generated by Django 4.2.11 on 2026-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("pin_reset", "PIN Reset"),
                ],
                default="verification",
                max_length=20,
            ),
        ),
    ]
