# Generated by Django 4.2.11 on 2026-05-30 09:55

import apps.authentication.crypto_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_hashed',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_masked',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=apps.authentication.crypto_utils.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_hashed',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_masked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_hashed',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_masked',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_hashed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_masked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=apps.authentication.crypto_utils.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=apps.authentication.crypto_utils.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=apps.authentication.crypto_utils.EncryptedTextField(blank=True, null=True),
        ),
    ]
