# Generated by Django 4.2.11 on 2026-05-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "__first__"),
        ("authentication", "0003_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="assigned_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="custom_admin.role",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("STAFF", "Staff"), ("SUPER_ADMIN", "Super Admin")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
